//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MajorsData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MajorsData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiosk.MajorsData", typeof(MajorsData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur at velit ac dui dictum dignissim eu vitae purus. Donec nec magna in enim volutpat volutpat vel sed elit. Integer hendrerit luctus efficitur. Nullam vitae eros in dui viverra vulputate. Morbi lobortis semper ex in commodo. In aliquam nisi sit amet turpis congue, nec lobortis mauris placerat. Sed lacinia rhoncus aliquam. Sed nunc diam, imperdiet in efficitur non, condimentum bibendum elit. Sed pulvinar tempor augue nec lacinia. Nullam sit amet [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 187.
        /// </summary>
        public static string CreditHours {
            get {
                return ResourceManager.GetString("CreditHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineering Technology.
        /// </summary>
        public static string DegreeName {
            get {
                return ResourceManager.GetString("DegreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Bachelor of Science -.
        /// </summary>
        public static string DegreesOffered {
            get {
                return ResourceManager.GetString("DegreesOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpaceX&amp;#x0a;Expedia&amp;#x0a;Amazon&amp;#x0a;Microsoft&amp;#x0a;International Game Technology&amp;#x0a;Intel Corporation&amp;#x0a;Garmin&amp;#x0a;Sandia National Laboratories.
        /// </summary>
        public static string Employers {
            get {
                return ResourceManager.GetString("Employers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1984.
        /// </summary>
        public static string YearOffered {
            get {
                return ResourceManager.GetString("YearOffered", resourceCulture);
            }
        }
    }
}
